version: '3.9'

services:
  app:
    container_name: airbnb-app
    build: .
    ports:
      - "${PORT:-8080}:8080"
      - "9229:9229" # Debug port
    volumes:
      - ./src:/app/src
    networks:
      - airbnb
    env_file:
      - .env

networks:
  airbnb:
