version: '3.9'

services:
  app:
    container_name: airbnb-app
    build: .
    command: ./scripts/run.sh
    ports:
      - "${APP_PORT:-8080}:8080"
      - "9229:9229" # Debug port
    volumes:
      - ./src:/app/src
      - ./scripts:/app/scripts
    networks:
      - airbnb
    env_file:
      - .env.docker
    depends_on:
      - mongo

  mongo:
    container_name: airbnb-mongo
    image: mongo
    ports:
      - "${MONGO_PORT:-27017}:27017"
    networks:
      - airbnb

networks:
  airbnb:
